version: "3.3"
services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: Mot_de_passe_root
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: Mot_de_passe_wordpress
            MYSQL_DATABASE: wordpress
    webserver:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./wordpress:/code
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - ./wordpress:/code
networks:
    wordpress:
        driver: "bridge"